safe:        false
auto:        false
server:      false
server_port: 4000

source:      ./_empty
destination: ./_site

future:      false
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date
